import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "OnlineClass",
  description: "Generated by create next app",
  keywords: "",
  creator: "OnlineClass",
  authors: {
    name: "OnlineClass",
    url: "",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
